import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AV Design - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.container}>
        <div className={"text-center"}>
          <div>
            <Link href={"/login"}>Login</Link>
          </div>
          <div>
            <Link href={"/dashboard"}>Dashboard</Link>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
