import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const Login: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AV Design - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Login
        <Link href={"/"}>Home</Link>
        <Link href={"/signup"}>Sign Up</Link>
      </main>

      <footer>Footer</footer>
    </div>
  );
};

export default Login;
