import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
// import authStyle from "../styles/auth.module.css";
import styles from "../styles/login.module.scss";

const Login: NextPage = () => {
  return (
    <>
    <Image src="/images/bg.webp" alt="background" layout="fill" />
    <div className={styles.wrapper}>
      <Head>
        <title>AV Design - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.divided}>
        <form className={styles.half}>
          <h1>Welcome Back</h1>
          <small>Enter your details below to continue using AV Designer.</small>
          <button type="submit" className={styles.loginbtn}>Sign in</button>
          <span className={styles.prompt}>New to AV Designer? Sign Up</span>
        </form>
        <span className={styles.divider}></span>
        <div className={styles.half}>
          <div className={styles.logo}><span className={styles.orange}>AV</span> DESIGNER</div>
        </div>
      </main>
    </div>
    </>
  );
};

export default Login;
