import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

const SignUp: NextPage = () => {
  return (
    <div>
      <Head>
        <title>AV Design - Sign Up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Welcome
        <Link href={"/login"}>Login</Link>
      </main>

      <footer>Footer</footer>
    </div>
  );
};

export default SignUp;
